### PR TITLE
Change to use umami-api, remove node-fetch

### PR DESCRIPTION
**Pull request by jakobbouchard**
Hey! Really like your work! Since I made my own API too, I wanted to know if you wanted to use it instead. It has typings, making it easier to use (in my opinion), and I already added a lot more API endpoints than those listed in the docs :)

### CODE REVIEW

**Comment by jakobbouchard** [comment]
I now have all the available endpoints programmed in.

**Comment by boly38** [comment]
Hi @jakobbouchard 

welcome and thanks for your contribution. 👏 

My side I have just a small experience with typescript, anyway your clone seems more advanced than mine, so ok to switch.

As it's usable from JavaScript this is ok for me.

Could you do this little change please:
- if possible: squash your 3 commit in a single one
- update readme : the umami client reference in [umami](https://github.com/boly38/action-umami-report#umami) section)

To fix audit, I will just update deps right now, 
you will need to rebase your squashed commit, and then I ll merge it (make it node fetch to dissapear)

**Comment by jakobbouchard** [comment]
Cool! I'll do this very soon, I've just been quite busy since I just started university :)

**Comment by jakobbouchard** [comment]
Hey @boly38! I just made the changes you requested :) I also updated to the latest version of my API client. If there's anything else, let me know!

**Comment by boly38** [comment]
merged with #30 ; thanks 🙏

**Pull request closed without merging**
